### ISSUE TITLE
Redundant .gitignore

### ISSUE THREAD

**Issue by rcass** [DHilscher/Inhabitent#2]
Inside the plugins folder there is a .gitignore, since we already have a gitignore in the root of our project (the root of the wp-content), the one in the plugins folder is unnecessary!

- [ ] Delete .gitignore in the plugin folder (it is extra)

**Comment by DHilscher** [comment]
I had already deleted that I guess it just never got deleted from github

**Comment by DHilscher** [comment]
oops it was the themes one I had deleted i found the plugin ones you mentioned and deleted them thanks :)

**Comment by rcass** [comment]
Perfect 💯  Everything looks good now 🎉
