### ISSUE TITLE
Namespacing functions

### ISSUE THREAD

**Issue by rcass** [DHilscher/Inhabitent#3]
In extras.php on line 70, to avoid possible global name errors (and just making things more readable), you just need to make your function name a little more descriptive.

Currently, you function name is ` function new_excerpt_more($more)`, since this function exists only for this theme a name something like `function inhabitent_excerpt_more($more)` would be better.

Hope that makes sense, just let me know if needs more explanation!

- [ ] Change function name on line 70 on extras.php to something more descriptive

**Comment by DHilscher** [comment]
fixed that function. Thanks Rose, fixing it also made me realize it was a duplicate of a lower one named what you wanted me to change it to! Apparently I worked on it in two spots ;)
