### ISSUE TITLE
Extra Font Files

### ISSUE THREAD

**Issue by rcass** [DHilscher/Inhabitent#4]
Inside of the font folder, there are just some extra folders and css files within them that need to be removed.

These are the folders that can be removed:
![screen shot 2017-08-18 at 10 01 04 am](https://user-images.githubusercontent.com/5028555/29469229-3819d98e-83fc-11e7-8d82-6bf29dd6c577.png)

Let me know if you have questions! 👍

**Comment by DHilscher** [comment]
done.
Thanks Rose!
