### ISSUE TITLE
Theme Check Error to resolve

### ISSUE THREAD

**Issue by rcass** [DHilscher/Inhabitent#5]
When I use theme check (suggested dev plugin mentioned previously), it finds this error:
![screen shot 2017-08-22 at 10 37 00 am](https://user-images.githubusercontent.com/5028555/29578952-08c0c8fa-8726-11e7-83cf-14d2c3ab07f4.png)

I highly recommend you address this, all you need to do is delete those characters and replaces them with the white space you want. 

Just a heads, weird invisible characters sometimes appear from copying and pasting. Could be from slack,etc.

**Comment by DHilscher** [comment]
oh weird, I fixed it thanks Rose!
